// Movie Data
const MOVIES_DATA = [
  {
    id: "1",
    title: "Avengers: Endgame",
    slug: "avengers-endgame",
    year: 2019,
    genre: ["Action", "Adventure", "Drama"],
    rating: 8.4,
    duration: "3h 1m",
    quality: "4K",
    language: "English",
    poster: "/placeholder.svg?height=400&width=300",
    backdrop: "/placeholder.svg?height=600&width=1200",
    description:
      "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
    director: "Anthony Russo, Joe Russo",
    cast: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo", "Chris Hemsworth", "Scarlett Johansson"],
    views: 2500000,
    isNew: false,
    isFeatured: true,
    isTrending: true,
    downloadUrl: "https://example.com/download/avengers-endgame",
    videoUrl: "https://example.com/watch/avengers-endgame",
    embedCode:
      '<iframe src="https://example.com/embed/avengers-endgame" width="100%" height="100%" allowfullscreen></iframe>',
  },
  {
    id: "2",
    title: "The Dark Knight",
    slug: "the-dark-knight",
    year: 2008,
    genre: ["Action", "Crime", "Drama"],
    rating: 9.0,
    duration: "2h 32m",
    quality: "HD",
    language: "English",
    poster: "/placeholder.svg?height=400&width=300",
    backdrop: "/placeholder.svg?height=600&width=1200",
    description:
      "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    director: "Christopher Nolan",
    cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Michael Caine", "Maggie Gyllenhaal"],
    views: 3200000,
    isNew: false,
    isFeatured: true,
    isTrending: true,
    downloadUrl: "https://example.com/download/the-dark-knight",
    videoUrl: "https://example.com/watch/the-dark-knight",
  },
  {
    id: "3",
    title: "Inception",
    slug: "inception",
    year: 2010,
    genre: ["Action", "Sci-Fi", "Thriller"],
    rating: 8.8,
    duration: "2h 28m",
    quality: "HD",
    language: "English",
    poster: "/placeholder.svg?height=400&width=300",
    backdrop: "/placeholder.svg?height=600&width=1200",
    description:
      "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    director: "Christopher Nolan",
    cast: ["Leonardo DiCaprio", "Marion Cotillard", "Tom Hardy", "Ellen Page", "Ken Watanabe"],
    views: 2800000,
    isNew: false,
    isFeatured: true,
    isTrending: false,
    downloadUrl: "https://example.com/download/inception",
    videoUrl: "https://example.com/watch/inception",
  },
  {
    id: "4",
    title: "Parasite",
    slug: "parasite",
    year: 2019,
    genre: ["Comedy", "Drama", "Thriller"],
    rating: 8.6,
    duration: "2h 12m",
    quality: "HD",
    language: "Korean",
    poster: "/placeholder.svg?height=400&width=300",
    backdrop: "/placeholder.svg?height=600&width=1200",
    description:
      "A poor family schemes to become employed by a wealthy family by infiltrating their household and posing as unrelated, highly qualified individuals.",
    director: "Bong Joon-ho",
    cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong", "Choi Woo-shik", "Park So-dam"],
    views: 1800000,
    isNew: true,
    isFeatured: false,
    isTrending: true,
    downloadUrl: "https://example.com/download/parasite",
    videoUrl: "https://example.com/watch/parasite",
  },
  {
    id: "5",
    title: "Spider-Man: No Way Home",
    slug: "spider-man-no-way-home",
    year: 2021,
    genre: ["Action", "Adventure", "Sci-Fi"],
    rating: 8.2,
    duration: "2h 28m",
    quality: "4K",
    language: "English",
    poster: "/placeholder.svg?height=400&width=300",
    backdrop: "/placeholder.svg?height=600&width=1200",
    description:
      "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
    director: "Jon Watts",
    cast: ["Tom Holland", "Zendaya", "Benedict Cumberbatch", "Jacob Batalon", "Jon Favreau"],
    views: 4200000,
    isNew: true,
    isFeatured: true,
    isTrending: true,
    downloadUrl: "https://example.com/download/spider-man-no-way-home",
    videoUrl: "https://example.com/watch/spider-man-no-way-home",
  },
  {
    id: "6",
    title: "The Godfather",
    slug: "the-godfather",
    year: 1972,
    genre: ["Crime", "Drama"],
    rating: 9.2,
    duration: "2h 55m",
    quality: "HD",
    language: "English",
    poster: "/placeholder.svg?height=400&width=300",
    backdrop: "/placeholder.svg?height=600&width=1200",
    description:
      "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    director: "Francis Ford Coppola",
    cast: ["Marlon Brando", "Al Pacino", "James Caan", "Diane Keaton", "Robert Duvall"],
    views: 2100000,
    isNew: false,
    isFeatured: true,
    isTrending: false,
    downloadUrl: "https://example.com/download/the-godfather",
    videoUrl: "https://example.com/watch/the-godfather",
  },
  {
    id: "7",
    title: "Pulp Fiction",
    slug: "pulp-fiction",
    year: 1994,
    genre: ["Crime", "Drama"],
    rating: 8.9,
    duration: "2h 34m",
    quality: "HD",
    language: "English",
    poster: "/placeholder.svg?height=400&width=300",
    backdrop: "/placeholder.svg?height=600&width=1200",
    description:
      "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    director: "Quentin Tarantino",
    cast: ["John Travolta", "Uma Thurman", "Samuel L. Jackson", "Bruce Willis", "Ving Rhames"],
    views: 1900000,
    isNew: false,
    isFeatured: false,
    isTrending: false,
    downloadUrl: "https://example.com/download/pulp-fiction",
    videoUrl: "https://example.com/watch/pulp-fiction",
  },
  {
    id: "8",
    title: "Interstellar",
    slug: "interstellar",
    year: 2014,
    genre: ["Adventure", "Drama", "Sci-Fi"],
    rating: 8.6,
    duration: "2h 49m",
    quality: "4K",
    language: "English",
    poster: "/placeholder.svg?height=400&width=300",
    backdrop: "/placeholder.svg?height=600&width=1200",
    description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    director: "Christopher Nolan",
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine", "Matt Damon"],
    views: 2600000,
    isNew: false,
    isFeatured: true,
    isTrending: false,
    downloadUrl: "https://example.com/download/interstellar",
    videoUrl: "https://example.com/watch/interstellar",
  },
  {
    id: "9",
    title: "The Matrix",
    slug: "the-matrix",
    year: 1999,
    genre: ["Action", "Sci-Fi"],
    rating: 8.7,
    duration: "2h 16m",
    quality: "HD",
    language: "English",
    poster: "/placeholder.svg?height=400&width=300",
    backdrop: "/placeholder.svg?height=600&width=1200",
    description:
      "A computer programmer is led to fight an underground war against powerful computers who have constructed his entire reality with a system called the Matrix.",
    director: "Lana Wachowski, Lilly Wachowski",
    cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss", "Hugo Weaving", "Gloria Foster"],
    views: 2300000,
    isNew: false,
    isFeatured: false,
    isTrending: true,
    downloadUrl: "https://example.com/download/the-matrix",
    videoUrl: "https://example.com/watch/the-matrix",
  },
  {
    id: "10",
    title: "Forrest Gump",
    slug: "forrest-gump",
    year: 1994,
    genre: ["Drama", "Romance"],
    rating: 8.8,
    duration: "2h 22m",
    quality: "HD",
    language: "English",
    poster: "/placeholder.svg?height=400&width=300",
    backdrop: "/placeholder.svg?height=600&width=1200",
    description:
      "The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate and other historical events unfold from the perspective of an Alabama man with an IQ of 75.",
    director: "Robert Zemeckis",
    cast: ["Tom Hanks", "Robin Wright", "Gary Sinise", "Sally Field", "Mykelti Williamson"],
    views: 2700000,
    isNew: false,
    isFeatured: false,
    isTrending: false,
    downloadUrl: "https://example.com/download/forrest-gump",
    videoUrl: "https://example.com/watch/forrest-gump",
  },
  {
    id: "11",
    title: "Breaking Bad",
    slug: "breaking-bad",
    year: 2008,
    genre: ["Crime", "Drama", "Thriller"],
    rating: 9.5,
    duration: "47m per episode",
    quality: "HD",
    language: "English",
    poster: "/placeholder.svg?height=400&width=300",
    backdrop: "/placeholder.svg?height=600&width=1200",
    description:
      "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family's future.",
    director: "Vince Gilligan",
    cast: ["Bryan Cranston", "Aaron Paul", "Anna Gunn", "RJ Mitte", "Dean Norris"],
    views: 3500000,
    isNew: false,
    isFeatured: true,
    isTrending: true,
    multipleDownloads: [
      {
        label: "Season 1",
        url: "https://example.com/download/breaking-bad-s1",
        embedCode:
          '<iframe src="https://example.com/embed/breaking-bad-s1" width="100%" height="100%" allowfullscreen></iframe>',
      },
      {
        label: "Season 2",
        url: "https://example.com/download/breaking-bad-s2",
        embedCode:
          '<iframe src="https://example.com/embed/breaking-bad-s2" width="100%" height="100%" allowfullscreen></iframe>',
      },
      {
        label: "Season 3",
        url: "https://example.com/download/breaking-bad-s3",
        embedCode:
          '<iframe src="https://example.com/embed/breaking-bad-s3" width="100%" height="100%" allowfullscreen></iframe>',
      },
      {
        label: "Season 4",
        url: "https://example.com/download/breaking-bad-s4",
        embedCode:
          '<iframe src="https://example.com/embed/breaking-bad-s4" width="100%" height="100%" allowfullscreen></iframe>',
      },
      {
        label: "Season 5",
        url: "https://example.com/download/breaking-bad-s5",
        embedCode:
          '<iframe src="https://example.com/embed/breaking-bad-s5" width="100%" height="100%" allowfullscreen></iframe>',
      },
    ],
  },
  {
    id: "12",
    title: "Game of Thrones",
    slug: "game-of-thrones",
    year: 2011,
    genre: ["Action", "Adventure", "Drama"],
    rating: 9.3,
    duration: "57m per episode",
    quality: "4K",
    language: "English",
    poster: "/placeholder.svg?height=400&width=300",
    backdrop: "/placeholder.svg?height=600&width=1200",
    description:
      "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.",
    director: "David Benioff, D.B. Weiss",
    cast: ["Peter Dinklage", "Lena Headey", "Emilia Clarke", "Kit Harington", "Sophie Turner"],
    views: 4800000,
    isNew: false,
    isFeatured: true,
    isTrending: false,
    multipleDownloads: [
      { label: "Season 1", url: "https://example.com/download/got-s1" },
      { label: "Season 2", url: "https://example.com/download/got-s2" },
      { label: "Season 3", url: "https://example.com/download/got-s3" },
      { label: "Season 4", url: "https://example.com/download/got-s4" },
      { label: "Season 5", url: "https://example.com/download/got-s5" },
      { label: "Season 6", url: "https://example.com/download/got-s6" },
      { label: "Season 7", url: "https://example.com/download/got-s7" },
      { label: "Season 8", url: "https://example.com/download/got-s8" },
    ],
  },
]

// Add more movies to reach a good collection
for (let i = 13; i <= 50; i++) {
  const genres = [
    "Action",
    "Comedy",
    "Drama",
    "Horror",
    "Romance",
    "Sci-Fi",
    "Thriller",
    "Animation",
    "Adventure",
    "Crime",
    "Fantasy",
    "Mystery",
  ]
  const qualities = ["HD", "4K", "CAM"]
  const languages = ["English", "Spanish", "French", "German", "Japanese", "Korean", "Hindi"]

  const randomGenres = genres.sort(() => 0.5 - Math.random()).slice(0, Math.floor(Math.random() * 3) + 1)
  const randomQuality = qualities[Math.floor(Math.random() * qualities.length)]
  const randomLanguage = languages[Math.floor(Math.random() * languages.length)]

  MOVIES_DATA.push({
    id: i.toString(),
    title: `Movie ${i}`,
    slug: `movie-${i}`,
    year: Math.floor(Math.random() * (2021 - 1970 + 1)) + 1970,
    genre: randomGenres,
    rating: Math.floor(Math.random() * (10 - 7 + 1)) + 7,
    duration: `${Math.floor(Math.random() * (3 - 1 + 1)) + 1}h ${Math.floor(Math.random() * 60)}m`,
    quality: randomQuality,
    language: randomLanguage,
    poster: "/placeholder.svg?height=400&width=300",
    backdrop: "/placeholder.svg?height=600&width=1200",
    description: "A placeholder description for the movie.",
    director: "Random Director",
    cast: ["Actor 1", "Actor 2", "Actor 3"],
    views: Math.floor(Math.random() * (10000000 - 1000000 + 1)) + 1000000,
    isNew: Math.random() > 0.5,
    isFeatured: Math.random() > 0.5,
    isTrending: Math.random() > 0.5,
  })
}
